version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apple/backend/gameMusic

permissions:
  - object: /home/ubuntu/apple/backend/gameMusic
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 300
      runas: ubuntu